-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 20:18:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbconnectx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbconnectx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbconnectx` DEFAULT CHARACTER SET utf8 ;
USE `dbconnectx` ;

-- -----------------------------------------------------
-- Table `dbconnectx`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(256) NOT NULL,
  `tipo_persona` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidopa` VARCHAR(45) NULL,
  `apellidoma` VARCHAR(45) NULL,
  `curp` VARCHAR(45) NULL,
  `recibo` VARCHAR(256) NULL,
  `estado` VARCHAR(10) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `upp` VARCHAR(45) NULL,
  `pgn` VARCHAR(45) NULL,
  `clave_rast` VARCHAR(45) NULL,
  `num_colmena` VARCHAR(45) NULL,
  `prod_anual` VARCHAR(45) NULL,
  `certificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `idpersona_UNIQUE` (`idpersona` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`apiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`apiarios` (
  `idapiarios` INT NOT NULL AUTO_INCREMENT,
  `idpersona` VARCHAR(45) NULL,
  `loc_api` VARCHAR(45) NULL,
  `tem_cosecha` VARCHAR(45) NULL,
  `mov_api` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idapiarios`),
  CONSTRAINT `fk_api_peri`
    FOREIGN KEY (`idapiarios`)
    REFERENCES `dbconnectx`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS