-- MySQL Script generated by MySQL Workbench
-- Mon May 13 10:06:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbconnectx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbconnectx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbconnectx` DEFAULT CHARACTER SET utf8 ;
USE `dbconnectx` ;

-- -----------------------------------------------------
-- Table `dbconnectx`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(50) NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(512) NULL,
  `imagen` VARCHAR(50) NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `fk_articulo_categoria_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_articulo_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbconnectx`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`apicultor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`apicultor` (
  `idapicultor` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NOT NULL,
  `num_colmena` INT NOT NULL,
  `geoloc_apiario` VARCHAR(200) NOT NULL,
  `prod_anual` INT NOT NULL,
  `temp_cosecha` VARCHAR(200) NOT NULL,
  `tipo_certificacion` VARCHAR(200) NOT NULL,
  `mueve_sus_colmena` VARCHAR(10) NOT NULL,
  `a_donde` VARCHAR(256) NOT NULL,
  `observaciones` VARCHAR(256) NOT NULL,
  `upp` VARCHAR(45) NOT NULL,
  `pgn` VARCHAR(45) NOT NULL,
  `clave_rast` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idapicultor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(256) NOT NULL,
  `tipo_documento` VARCHAR(20) NULL,
  `num_documento` VARCHAR(15) NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_Pidpersona_Aidpersona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `dbconnectx`.`apicultor` (`idapicultor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(30) NULL,
  `num_comprobante` VARCHAR(30) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_ingreso_persona_idx` (`idproveedor` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_persona`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `dbconnectx`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`detalle_ingreso` (
  `iddetalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `idingreso` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_compra` DECIMAL(11,2) NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`iddetalle_ingreso`),
  INDEX `fk_detalle_ingreso_articulo_idx` (`idarticulo` ASC) VISIBLE,
  INDEX `fk_detalle_ingreso_idx` (`idingreso` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `dbconnectx`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ingreso_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbconnectx`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `tipo_comprobante` VARCHAR(40) NOT NULL,
  `serie_comprobante` VARCHAR(30) NOT NULL,
  `num_comprobante` VARCHAR(40) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total_venta` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbconnectx`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconnectx`.`Detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconnectx`.`Detalle_venta` (
  `idDetalle_venta` INT NOT NULL AUTO_INCREMENT,
  `idventa` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idDetalle_venta`),
  INDEX `fk_detalle_venta_articulo_idx` (`idarticulo` ASC) VISIBLE,
  INDEX `fk_detalle_venta_idx` (`idventa` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbconnectx`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta`
    FOREIGN KEY (`idventa`)
    REFERENCES `dbconnectx`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
